name:                projekat
version:             0.1.0.0
github:              "githubuser/projekat"
license:             BSD3
author:              "Nikola Borjan"
maintainer:          "nikola.borjan@yahoo.com"
copyright:           "2021 Nikola Borjan, Marko Bura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/projekat#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- process
- hashable
- split
- text

library:
  source-dirs: src

executables:
  projekat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projekat

tests:
  projekat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projekat
